"""Initial migration: create all tables

Revision ID: 777817938b66
Revises: 
Create Date: 2025-10-30 15:25:27.129603

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "777817938b66"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "enablers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("planned_delivery_date", sa.DateTime(), nullable=False),
        sa.Column("actual_delivery_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("criticality", sa.String(length=50), nullable=False),
        sa.Column("responsible_person", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_enablers_criticality"), "enablers", ["criticality"], unique=False)
    op.create_index(op.f("ix_enablers_id"), "enablers", ["id"], unique=False)
    op.create_index(op.f("ix_enablers_name"), "enablers", ["name"], unique=False)
    op.create_index(
        op.f("ix_enablers_planned_delivery_date"),
        "enablers",
        ["planned_delivery_date"],
        unique=False,
    )
    op.create_index(op.f("ix_enablers_project_id"), "enablers", ["project_id"], unique=False)
    op.create_index(op.f("ix_enablers_status"), "enablers", ["status"], unique=False)
    op.create_index(op.f("ix_enablers_type"), "enablers", ["type"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("assignee", sa.String(length=100), nullable=True),
        sa.Column("is_milestone", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_name"), "tasks", ["name"], unique=False)
    op.create_index(op.f("ix_tasks_priority"), "tasks", ["priority"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("enabler_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("event_date", sa.DateTime(), nullable=False),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["enabler_id"], ["enablers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_events_enabler_id"), "calendar_events", ["enabler_id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_event_date"), "calendar_events", ["event_date"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_event_type"), "calendar_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_calendar_events_id"), "calendar_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_calendar_events_project_id"), "calendar_events", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_events_task_id"), "calendar_events", ["task_id"], unique=False
    )
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("predecessor_task_id", sa.Integer(), nullable=False),
        sa.Column("successor_task_id", sa.Integer(), nullable=False),
        sa.Column("dependency_type", sa.String(length=10), nullable=False),
        sa.Column("lag_days", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["predecessor_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["successor_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dependencies_dependency_type"), "dependencies", ["dependency_type"], unique=False
    )
    op.create_index(op.f("ix_dependencies_id"), "dependencies", ["id"], unique=False)
    op.create_index(
        op.f("ix_dependencies_predecessor_task_id"),
        "dependencies",
        ["predecessor_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dependencies_successor_task_id"),
        "dependencies",
        ["successor_task_id"],
        unique=False,
    )
    op.create_table(
        "enabler_impacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enabler_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("impact_type", sa.String(length=50), nullable=False),
        sa.Column("impact_description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["enabler_id"], ["enablers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enabler_impacts_enabler_id"), "enabler_impacts", ["enabler_id"], unique=False
    )
    op.create_index(op.f("ix_enabler_impacts_id"), "enabler_impacts", ["id"], unique=False)
    op.create_index(
        op.f("ix_enabler_impacts_impact_type"), "enabler_impacts", ["impact_type"], unique=False
    )
    op.create_index(
        op.f("ix_enabler_impacts_task_id"), "enabler_impacts", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enabler_impacts_task_id"), table_name="enabler_impacts")
    op.drop_index(op.f("ix_enabler_impacts_impact_type"), table_name="enabler_impacts")
    op.drop_index(op.f("ix_enabler_impacts_id"), table_name="enabler_impacts")
    op.drop_index(op.f("ix_enabler_impacts_enabler_id"), table_name="enabler_impacts")
    op.drop_table("enabler_impacts")
    op.drop_index(op.f("ix_dependencies_successor_task_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_predecessor_task_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_dependency_type"), table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index(op.f("ix_calendar_events_task_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_project_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_event_type"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_event_date"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_enabler_id"), table_name="calendar_events")
    op.drop_table("calendar_events")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_priority"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_name"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_enablers_type"), table_name="enablers")
    op.drop_index(op.f("ix_enablers_status"), table_name="enablers")
    op.drop_index(op.f("ix_enablers_project_id"), table_name="enablers")
    op.drop_index(op.f("ix_enablers_planned_delivery_date"), table_name="enablers")
    op.drop_index(op.f("ix_enablers_name"), table_name="enablers")
    op.drop_index(op.f("ix_enablers_id"), table_name="enablers")
    op.drop_index(op.f("ix_enablers_criticality"), table_name="enablers")
    op.drop_table("enablers")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
